# numpy 

In [3]:
import numpy as np

In [2]:
mylist=[1,2,3]

In [3]:
arr=np.array([1,2,3])

In [5]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3])

In [8]:
mylist

[1, 2, 3]

In [10]:
myArrL= np.array(mylist)

In [11]:
myArrL

array([1, 2, 3])

In [13]:
#  2d array

mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
mat.shape

(3, 3)

In [16]:
myArrL.shape

(3,)

In [18]:
mat[1,2]

6

In [19]:
mat[2,2]

9

In [22]:
# arrange function in numpy
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
arrn=np.arange(0,11,2).reshape(2,3)

In [5]:
arrn.shape

(2, 3)

In [6]:
arrn

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [27]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
np.ones(3)

array([1., 1., 1.])

In [30]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [33]:
np.eye(10)
#gives identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
#random function
arrR=np.random.rand(5)

In [35]:
arrR

array([0.43582385, 0.14774689, 0.15924433, 0.24381235, 0.44712684])

In [36]:
arrr=np.random.randint(0,100,10).reshape(5,2)

In [37]:
arrr

array([[50, 98],
       [43, 81],
       [76, 24],
       [40, 91],
       [58, 71]])

In [38]:
np.random.seed(101)

In [39]:
arrR.argmin()

1

In [40]:
arrR.mean()

0.28675085003992296

In [41]:
nArr = np.arange(0,11,2)

In [42]:
nArr[:]

array([ 0,  2,  4,  6,  8, 10])

In [44]:
nArr[1:-2]

array([2, 4, 6])

In [45]:
nArr[1:-2]=100

In [47]:
nArr

array([  0, 100, 100, 100,   8,  10])

In [56]:
slice_of_Array= nArr[0:4]

In [57]:
slice_of_Array

array([  0, 100, 100, 100])

In [59]:
slice_of_Array[:]= 200

In [60]:
slice_of_Array

array([200, 200, 200, 200])

In [61]:
nArr

array([200, 200, 200, 200,   8,  10])

In [63]:
arr_copy [:]=1000

In [64]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000])

In [65]:
nArr

array([200, 200, 200, 200,   8,  10])

In [66]:
arr_2d=np.arange(0,100,1).reshape(10,10)


In [67]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [69]:
arr_2d[2,5]

25

In [70]:
arr_2d[2:,:5]

array([[20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54],
       [60, 61, 62, 63, 64],
       [70, 71, 72, 73, 74],
       [80, 81, 82, 83, 84],
       [90, 91, 92, 93, 94]])

In [71]:
arr_2d>30

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [72]:
#numpy operations
arr= np.arange(0,10)

In [73]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [75]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [76]:
arr/arr  # nan bcz 1/0

<ipython-input-76-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [77]:
1/arr

<ipython-input-77-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [82]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [81]:
np.log(arr)

<ipython-input-81-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
# exercises 

In [84]:
#create an array of 10 zeros
arr=np.ones(10)

In [85]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [86]:
# create an array of 10 ones
arr=np.zeros(10)

In [87]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [90]:
arr=np.ones(10)*5

In [91]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [92]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [93]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [94]:
# even numbers bet 10 to 50
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [ ]:
np.arange

In [95]:
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])